import Link from "next/link";
import { philosophers } from "@/data/philosophers";
import { PhilosopherAvatar } from "@/src/components/philosopher-visuals/PhilosopherAvatar";

const comparePairs = [["mencius", "xunzi"], ["zhu_xi", "wang_yangming"], ["bentham", "mill"], ["hobbes", "locke"], ["rawls", "nozick"], ["yi_hwang", "yi_i"]] as const;

export function VisualStudySections() {
  return <section className="space-y-9">
    <div id="face-finder" className="rounded-3xl border border-white/15 bg-slate-900/65 p-6 shadow-premium backdrop-blur-xl md:p-8">
      <h3 className="text-2xl font-bold">상징으로 기억하는 철학자</h3>
      <p className="mt-2 text-sm text-slate-300">철학자의 핵심 개념을 상징과 키워드로 먼저 잡아보세요.</p>
      <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{philosophers.map((p) => <Link key={p.id} href={`/philosophers/${p.id}`} className="group min-w-0 rounded-2xl border border-white/15 bg-gradient-to-b from-slate-900/80 to-slate-950/75 p-5 transition duration-300 hover:-translate-y-0.5 hover:border-atlas-cyan/50 hover:shadow-[0_14px_30px_rgba(56,189,248,0.18)]"><div className="flex items-start gap-4"><PhilosopherAvatar id={p.id} name={p.name} size={80} /><div className="min-w-0" style={{ wordBreak: "keep-all", whiteSpace: "normal" }}><p className="text-lg font-semibold leading-tight">{p.name}</p><p className="mt-1 text-xs text-atlas-cyan">{p.symbol} · {p.reviewStatus}</p><p className="mt-2 text-sm text-slate-300">{p.oneLine}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{p.coreConcepts.slice(0, 3).map((c) => <span key={c} className="rounded-full border border-white/25 bg-white/[0.05] px-2.5 py-1 text-xs text-slate-200">{c}</span>)}</div></Link>)}</div>
    </div>

    <div className="rounded-3xl border border-white/15 bg-slate-900/65 p-6 shadow-premium backdrop-blur-xl md:p-8"><h3 className="text-2xl font-bold">헷갈리는 철학자 비교 카드</h3><p className="mt-2 text-sm text-slate-300">시험에서 자주 섞이는 사상가를 한 장으로 비교해요.</p><div className="mt-5 grid gap-4 xl:grid-cols-2">{comparePairs.map(([l, r]) => {const left = philosophers.find(p => p.id === l)!; const right = philosophers.find(p => p.id === r)!; return <article key={l + r} className="min-w-0 rounded-2xl border border-white/15 bg-white/[0.04] p-5"><div className="grid items-stretch gap-3 md:grid-cols-[1fr_auto_1fr]"><Mini p={left} /><div className="flex items-center justify-center text-sm font-medium tracking-widest text-atlas-cyan/80">VS</div><Mini p={right} /></div><p className="mt-4 text-sm text-slate-200" style={{ wordBreak: "keep-all" }}>한 줄 차이: {left.keyStandard} ↔ {right.keyStandard}</p><p className="mt-2 text-xs text-slate-300">핵심 기준: {left.name}({left.keyStandard}) / {right.name}({right.keyStandard})</p><p className="mt-2 text-xs text-amber-200">시험 함정: {left.trapPreview} · {right.trapPreview}</p><Link href="#lab" className="mt-3 inline-block rounded-lg border border-atlas-cyan/45 bg-atlas-cyan/10 px-3 py-1.5 text-xs text-atlas-cyan">비교 실험실로 이동</Link></article>;})}</div></div>
  </section>;
}

function Mini({ p }: { p: (typeof philosophers)[number] }) { return <div className="min-w-0 rounded-xl border border-white/15 bg-slate-950/55 p-3 text-left"><div className="flex items-center gap-3"><PhilosopherAvatar id={p.id} name={p.name} size={58} /><div className="min-w-0" style={{ wordBreak: "keep-all", whiteSpace: "normal" }}><p className="text-sm font-semibold">{p.name}</p><p className="text-xs text-slate-300">{p.oneLine}</p></div></div></div>; }

export function OneCutSummaryCard({ id }: { id: string }) { const p = philosophers.find((item) => item.id === id); if (!p) return null; return <article className="rounded-2xl border border-white/15 bg-slate-900/60 p-4"><div className="flex min-w-0 gap-3"><PhilosopherAvatar id={p.id} name={p.name} size={72} /><div className="min-w-0" style={{ wordBreak: "keep-all", whiteSpace: "normal" }}><h4 className="font-semibold">{p.name}</h4><p className="text-xs text-slate-300">{p.oneLine}</p><p className="mt-2 text-xs">개념: {p.coreConcepts.slice(0, 3).join(", ")}</p><ul className="mt-2 list-disc pl-4 text-xs text-slate-200"><li>{p.mustKnow[0]}</li></ul><p className="mt-1 text-xs text-amber-200">시험 경고: {p.examWarning}</p></div></div></article>; }
