import Link from "next/link";
import { philosophers } from "@/data/philosophers";
import { IssueTopic } from "@/src/types/issueTopic";

type Props = { topic: IssueTopic };

const nameById = Object.fromEntries(philosophers.map((p) => [p.id, p.name]));

export function IssueDetailPanel({ topic }: Props) {
  return <article className="premium-card p-6 md:p-7"><p className="eyebrow">질문 → 논점 → 비교</p><h3 className="mt-3 text-2xl font-semibold tracking-tight">{topic.title}</h3><p className="mt-4 rounded-2xl border border-white/10 bg-white/[0.03] p-4 text-base leading-relaxed text-slate-100">Q. {topic.question}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><Info title="논점 핵심" value={topic.keyContrast} /><Info title="시험 포인트" value={topic.examPoint} /><Info title="자주 틀리는 함정" value={topic.commonTrap} /></div><div className="mt-6 rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs tracking-[0.18em] text-slate-400">개념 축으로 위치 잡기</p><div className="mt-3 flex items-center justify-between text-xs text-slate-300"><span>{topic.conceptAxis.leftLabel}</span><span>{topic.conceptAxis.rightLabel}</span></div><div className="mt-2 h-1 rounded-full bg-white/10" /><div className="mt-4 space-y-3">{topic.conceptAxis.positions.map((pos) => <div key={`${topic.id}-${pos.philosopherId}`}><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-100">{pos.label}</span><span className="text-xs text-slate-400">{pos.position}%</span></div><div className="mt-2 h-2 rounded-full bg-white/10"><div className="h-2 rounded-full bg-gradient-to-r from-atlas-cyan/70 to-violet-300/70" style={{ width: `${pos.position}%` }} /></div><p className="mt-1 text-xs text-slate-300">{pos.description}</p></div>)}</div></div><div className="mt-6"><p className="text-sm font-medium text-slate-100">관련 철학자</p><div className="mt-3 flex flex-wrap gap-2">{topic.relatedPhilosophers.map((id) => <Link key={id} href={`/philosophers/${id}`} className="rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-sm text-slate-100 hover:border-white/35">{nameById[id] ?? id}</Link>)}</div></div><div className="mt-6"><p className="text-sm font-medium text-slate-100">바로 비교하기</p><div className="mt-3 grid gap-3">{topic.comparePairs.map((pair, idx) => <div key={`${pair.a}-${pair.b}-${idx}`} className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><p className="text-sm font-medium text-cyan-100">{nameById[pair.a] ?? pair.a} vs {nameById[pair.b] ?? pair.b}</p><p className="mt-2 text-sm text-slate-200">한 줄 차이: {pair.oneLineDifference}</p><p className="mt-1 text-xs text-amber-100">시험 함정: {pair.examTrap}</p></div>)}</div></div></article>;
}

function Info({ title, value }: { title: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><p className="text-xs tracking-[0.12em] text-slate-400">{title}</p><p className="mt-2 text-sm leading-relaxed text-slate-100">{value}</p></div>; }
